# Snap-It Server 애플리케이션을 위한 기본 값 설정
replicaCount: 1

namespace: snapit-word2voc

image:
  repository: ghcr.io/chabinhwang/snap-it-word2vec
  tag: 1693b5fa2ebf563a051205b1dc90f46214357a2e
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: my-registry-secret

service:
  type: NodePort
  port: 8000
  nodePort: 32765


# 리소스 제한
resources:
  limits:
    cpu: 1000m
    memory: 5120Mi
  requests:
    cpu: 500m
    memory: 4096Mi

autoscaling:
  enabled: true # 자동 확장 활성화
  minReplicas: 1 # 최소 2개의 파드 생성
  maxReplicas: 2 # 최대 2개의 파드 생성
  targetCPUUtilizationPercentage: 90 # 90% 사용률 유지

ingress:
  enabled: false 

secrets:
  name: my-registry-secret