apiVersion: v1
kind: PersistentVolume
metadata:
  name: word2vec-model-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/data/models"  # 호스트 시스템의 경로
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: word2vec-model-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: local 